# Test: Deckhouse CRD enum validations
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: test-module
spec:
  version: "1"  # ERROR: should be integer, not string
  enabled: yes  # ERROR: should be true/false, not yes
  settings:
    key: value
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: test-nodegroup
spec:
  nodeType: cloud-ephemeral  # ERROR: should be CloudEphemeral
  cloudInstances:
    minPerZone: 1
    maxPerZone: 3
---
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: test-ingress
spec:
  ingressClass: nginx
  inlet: loadbalancer  # ERROR: should be LoadBalancer
---
apiVersion: deckhouse.io/v1
kind: ClusterAuthorizationRule
metadata:
  name: test-rule
spec:
  subjects:
    - kind: User
      name: admin
  accessLevel: admin  # ERROR: should be Admin
---
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLogDestination
metadata:
  name: test-logs
spec:
  type: loki  # ERROR: should be Loki
  loki:
    endpoint: http://loki:3100
---
apiVersion: deckhouse.io/v1alpha1
kind: VirtualMachine
metadata:
  name: test-vm
spec:
  virtualMachineClassName: generic
  runPolicy: always-on  # ERROR: should be AlwaysOn
  osType: linux  # ERROR: should be Generic or Windows
  bootloader: bios  # ERROR: should be BIOS
  cpu:
    cores: 2
  memory:
    size: 4Gi
  blockDeviceRefs:
    - kind: VirtualDisk
      name: disk1
