# Test: Deckhouse CRD validation
apiVersion: deckhouse.io/v1alpha1
kind: ModuleConfig
metadata:
  name: prometheus
spec:
  version: 1
  enabled: true
  settings:
    retentionDays: 15
    storageClass: fast-storage
---
apiVersion: deckhouse.io/v1
kind: NodeGroup
metadata:
  name: worker
spec:
  nodeType: CloudEphemeral
  cloudInstances:
    minPerZone: 1
    maxPerZone: 3
    classReference:
      kind: OpenStackInstanceClass
      name: worker
---
apiVersion: deckhouse.io/v1
kind: IngressNginxController
metadata:
  name: main
spec:
  ingressClass: nginx
  inlet: LoadBalancer
  loadBalancer:
    sourceRanges:
      - 0.0.0.0/0
---
apiVersion: deckhouse.io/v1
kind: DexAuthenticator
metadata:
  name: my-app
spec:
  applicationDomain: myapp.example.com
  sendAuthorizationHeader: true
  applicationIngressCertificateSecretName: myapp-tls
---
apiVersion: deckhouse.io/v1alpha1
kind: ClusterLogDestination
metadata:
  name: loki
spec:
  type: Loki
  loki:
    endpoint: http://loki.monitoring:3100
